apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cargo-cls
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cargo-cls
    spec:
      containers:
      - name: cargo-cls
        image: tz70s/cargo-cls:0.1.3
        ports:
        - containerPort: 8080
        env:
        - name: CARGO_MONGO_HOST
          value: cargo-store-mongodb.default.svc.cluster.local
        - name: CARGO_ARM_HOST
          value: engine.default.svc.cluster.local
        - name: CARGO_AUTONOMOUS_HOST
          value: engine.default.svc.cluster.local
        - name: CARGO_SHELF_HOST
          value: engine.default.svc.cluster.local
        args:
        - -Dlogback.log.level=INFO