apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cargo-cls
spec:
  replicas: 2
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: cargo-cls
    spec:
      containers:
      - name: cargo-cls
        image: tz70s/cargo-cls:0.1
        ports:
        - containerPort: 8080
        env:
        - name: CARGO_MONGO_HOST
          value: cargo-store-mongodb.default.svc.cluster.local
        - name: CARGO_ARM_HOST
          value: 140.112.42.110:4567
        - name: CARGO_SHELF_HOST
          value: cargo-shelf.default.svc.cluster.local