apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: engine
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
      - name: engine
        image: tz70s/engine:0.1
        ports:
        - containerPort: 8080
        env:
        - name: CARGO_MONGO_HOST
          value: cargo-store-mongodb.default.svc.cluster.local
        - name: CARGO_ARM_HOST
          value: engine.default.svc.cluster.local
        - name: CARGO_AUTONOMOUS_HOST
          value: engine.default.svc.cluster.local
        - name: CARGO_SHELF_HOST
          value: engine.default.svc.cluster.local
        args:
        - -Dlogback.log.level=DEBUG